# Generated by Django 4.2.14 on 2024-07-17 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('inquiry', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_status', models.CharField(blank=True, choices=[('Angefragt', 'Angefragt'), ('Bestätigt', 'Bestätigt'), ('Storniert', 'Storniert')], default='Angefragt', max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('booking_item', models.CharField(choices=[('Obere Ferienwohnung', 'Obere Ferienwohnung'), ('Untere Ferienwohnung', 'Untere Ferienwohnung'), ('Gesamtes Haus', 'Gesamtes Haus')], max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('amount_guests', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=100)),
                ('nationality', models.CharField(choices=[('Deutsch', 'Deutsch'), ('Andere / Other', 'Andere / Other')], max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('animals', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(max_length=4000)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
